name: My First Workflow 

on : push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: list and read files
          run: |
           echo "My First Github actions job"
           ls -ltra
           cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I'M A DRAGON......RWAR">> dragon.txt



